name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MoonBit Toolchain
        uses: hustcer/setup-moonbit@v1

      - name: Check MoonBit Version
        run: moon version --all

      - name: Check Code Formatting
        run: moon fmt --check

      - name: Check Types and Warnings
        run: moon check --deny-warn

      - name: Run Tests
        run: moon test --deny-warn

      - name: Generate Public Interfaces (moon info)
        run: moon info
